/* automatically generated by rust-bindgen 0.72.1 */

pub const RLGL_VERSION: &[u8; 4] = b"6.0\0";
pub const RL_DEFAULT_BATCH_BUFFER_ELEMENTS: u32 = 8192;
pub const RL_DEFAULT_BATCH_BUFFERS: u32 = 1;
pub const RL_DEFAULT_BATCH_DRAWCALLS: u32 = 256;
pub const RL_DEFAULT_BATCH_MAX_TEXTURE_UNITS: u32 = 4;
pub const RL_MAX_MATRIX_STACK_SIZE: u32 = 32;
pub const RL_MAX_SHADER_LOCATIONS: u32 = 32;
pub const RL_CULL_DISTANCE_NEAR: f64 = 0.05;
pub const RL_CULL_DISTANCE_FAR: f64 = 4000.0;
pub const RL_TEXTURE_WRAP_S: u32 = 10242;
pub const RL_TEXTURE_WRAP_T: u32 = 10243;
pub const RL_TEXTURE_MAG_FILTER: u32 = 10240;
pub const RL_TEXTURE_MIN_FILTER: u32 = 10241;
pub const RL_TEXTURE_FILTER_NEAREST: u32 = 9728;
pub const RL_TEXTURE_FILTER_LINEAR: u32 = 9729;
pub const RL_TEXTURE_FILTER_MIP_NEAREST: u32 = 9984;
pub const RL_TEXTURE_FILTER_NEAREST_MIP_LINEAR: u32 = 9986;
pub const RL_TEXTURE_FILTER_LINEAR_MIP_NEAREST: u32 = 9985;
pub const RL_TEXTURE_FILTER_MIP_LINEAR: u32 = 9987;
pub const RL_TEXTURE_FILTER_ANISOTROPIC: u32 = 12288;
pub const RL_TEXTURE_MIPMAP_BIAS_RATIO: u32 = 16384;
pub const RL_TEXTURE_WRAP_REPEAT: u32 = 10497;
pub const RL_TEXTURE_WRAP_CLAMP: u32 = 33071;
pub const RL_TEXTURE_WRAP_MIRROR_REPEAT: u32 = 33648;
pub const RL_TEXTURE_WRAP_MIRROR_CLAMP: u32 = 34626;
pub const RL_MODELVIEW: u32 = 5888;
pub const RL_PROJECTION: u32 = 5889;
pub const RL_TEXTURE: u32 = 5890;
pub const RL_LINES: u32 = 1;
pub const RL_TRIANGLES: u32 = 4;
pub const RL_QUADS: u32 = 7;
pub const RL_UNSIGNED_BYTE: u32 = 5121;
pub const RL_FLOAT: u32 = 5126;
pub const RL_STREAM_DRAW: u32 = 35040;
pub const RL_STREAM_READ: u32 = 35041;
pub const RL_STREAM_COPY: u32 = 35042;
pub const RL_STATIC_DRAW: u32 = 35044;
pub const RL_STATIC_READ: u32 = 35045;
pub const RL_STATIC_COPY: u32 = 35046;
pub const RL_DYNAMIC_DRAW: u32 = 35048;
pub const RL_DYNAMIC_READ: u32 = 35049;
pub const RL_DYNAMIC_COPY: u32 = 35050;
pub const RL_FRAGMENT_SHADER: u32 = 35632;
pub const RL_VERTEX_SHADER: u32 = 35633;
pub const RL_COMPUTE_SHADER: u32 = 37305;
pub const RL_ZERO: u32 = 0;
pub const RL_ONE: u32 = 1;
pub const RL_SRC_COLOR: u32 = 768;
pub const RL_ONE_MINUS_SRC_COLOR: u32 = 769;
pub const RL_SRC_ALPHA: u32 = 770;
pub const RL_ONE_MINUS_SRC_ALPHA: u32 = 771;
pub const RL_DST_ALPHA: u32 = 772;
pub const RL_ONE_MINUS_DST_ALPHA: u32 = 773;
pub const RL_DST_COLOR: u32 = 774;
pub const RL_ONE_MINUS_DST_COLOR: u32 = 775;
pub const RL_SRC_ALPHA_SATURATE: u32 = 776;
pub const RL_CONSTANT_COLOR: u32 = 32769;
pub const RL_ONE_MINUS_CONSTANT_COLOR: u32 = 32770;
pub const RL_CONSTANT_ALPHA: u32 = 32771;
pub const RL_ONE_MINUS_CONSTANT_ALPHA: u32 = 32772;
pub const RL_FUNC_ADD: u32 = 32774;
pub const RL_MIN: u32 = 32775;
pub const RL_MAX: u32 = 32776;
pub const RL_FUNC_SUBTRACT: u32 = 32778;
pub const RL_FUNC_REVERSE_SUBTRACT: u32 = 32779;
pub const RL_BLEND_EQUATION: u32 = 32777;
pub const RL_BLEND_EQUATION_RGB: u32 = 32777;
pub const RL_BLEND_EQUATION_ALPHA: u32 = 34877;
pub const RL_BLEND_DST_RGB: u32 = 32968;
pub const RL_BLEND_SRC_RGB: u32 = 32969;
pub const RL_BLEND_DST_ALPHA: u32 = 32970;
pub const RL_BLEND_SRC_ALPHA: u32 = 32971;
pub const RL_BLEND_COLOR: u32 = 32773;
pub const RL_READ_FRAMEBUFFER: u32 = 36008;
pub const RL_DRAW_FRAMEBUFFER: u32 = 36009;
pub const RL_DEFAULT_SHADER_ATTRIB_LOCATION_POSITION: u32 = 0;
pub const RL_DEFAULT_SHADER_ATTRIB_LOCATION_TEXCOORD: u32 = 1;
pub const RL_DEFAULT_SHADER_ATTRIB_LOCATION_NORMAL: u32 = 2;
pub const RL_DEFAULT_SHADER_ATTRIB_LOCATION_COLOR: u32 = 3;
pub const RL_DEFAULT_SHADER_ATTRIB_LOCATION_TANGENT: u32 = 4;
pub const RL_DEFAULT_SHADER_ATTRIB_LOCATION_TEXCOORD2: u32 = 5;
pub const RL_DEFAULT_SHADER_ATTRIB_LOCATION_INDICES: u32 = 6;
pub const RL_DEFAULT_SHADER_ATTRIB_LOCATION_BONEINDICES: u32 = 7;
pub const RL_DEFAULT_SHADER_ATTRIB_LOCATION_BONEWEIGHTS: u32 = 8;
pub const RL_DEFAULT_SHADER_ATTRIB_LOCATION_INSTANCETRANSFORM: u32 = 9;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Matrix {
    pub m0: f32,
    pub m4: f32,
    pub m8: f32,
    pub m12: f32,
    pub m1: f32,
    pub m5: f32,
    pub m9: f32,
    pub m13: f32,
    pub m2: f32,
    pub m6: f32,
    pub m10: f32,
    pub m14: f32,
    pub m3: f32,
    pub m7: f32,
    pub m11: f32,
    pub m15: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Matrix"][::std::mem::size_of::<Matrix>() - 64usize];
    ["Alignment of Matrix"][::std::mem::align_of::<Matrix>() - 4usize];
    ["Offset of field: Matrix::m0"][::std::mem::offset_of!(Matrix, m0) - 0usize];
    ["Offset of field: Matrix::m4"][::std::mem::offset_of!(Matrix, m4) - 4usize];
    ["Offset of field: Matrix::m8"][::std::mem::offset_of!(Matrix, m8) - 8usize];
    ["Offset of field: Matrix::m12"][::std::mem::offset_of!(Matrix, m12) - 12usize];
    ["Offset of field: Matrix::m1"][::std::mem::offset_of!(Matrix, m1) - 16usize];
    ["Offset of field: Matrix::m5"][::std::mem::offset_of!(Matrix, m5) - 20usize];
    ["Offset of field: Matrix::m9"][::std::mem::offset_of!(Matrix, m9) - 24usize];
    ["Offset of field: Matrix::m13"][::std::mem::offset_of!(Matrix, m13) - 28usize];
    ["Offset of field: Matrix::m2"][::std::mem::offset_of!(Matrix, m2) - 32usize];
    ["Offset of field: Matrix::m6"][::std::mem::offset_of!(Matrix, m6) - 36usize];
    ["Offset of field: Matrix::m10"][::std::mem::offset_of!(Matrix, m10) - 40usize];
    ["Offset of field: Matrix::m14"][::std::mem::offset_of!(Matrix, m14) - 44usize];
    ["Offset of field: Matrix::m3"][::std::mem::offset_of!(Matrix, m3) - 48usize];
    ["Offset of field: Matrix::m7"][::std::mem::offset_of!(Matrix, m7) - 52usize];
    ["Offset of field: Matrix::m11"][::std::mem::offset_of!(Matrix, m11) - 56usize];
    ["Offset of field: Matrix::m15"][::std::mem::offset_of!(Matrix, m15) - 60usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rlVertexBuffer {
    pub elementCount: ::std::os::raw::c_int,
    pub vertices: *mut f32,
    pub texcoords: *mut f32,
    pub normals: *mut f32,
    pub colors: *mut ::std::os::raw::c_uchar,
    pub indices: *mut ::std::os::raw::c_uint,
    pub vaoId: ::std::os::raw::c_uint,
    pub vboId: [::std::os::raw::c_uint; 5usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rlVertexBuffer"][::std::mem::size_of::<rlVertexBuffer>() - 72usize];
    ["Alignment of rlVertexBuffer"][::std::mem::align_of::<rlVertexBuffer>() - 8usize];
    ["Offset of field: rlVertexBuffer::elementCount"]
        [::std::mem::offset_of!(rlVertexBuffer, elementCount) - 0usize];
    ["Offset of field: rlVertexBuffer::vertices"]
        [::std::mem::offset_of!(rlVertexBuffer, vertices) - 8usize];
    ["Offset of field: rlVertexBuffer::texcoords"]
        [::std::mem::offset_of!(rlVertexBuffer, texcoords) - 16usize];
    ["Offset of field: rlVertexBuffer::normals"]
        [::std::mem::offset_of!(rlVertexBuffer, normals) - 24usize];
    ["Offset of field: rlVertexBuffer::colors"]
        [::std::mem::offset_of!(rlVertexBuffer, colors) - 32usize];
    ["Offset of field: rlVertexBuffer::indices"]
        [::std::mem::offset_of!(rlVertexBuffer, indices) - 40usize];
    ["Offset of field: rlVertexBuffer::vaoId"]
        [::std::mem::offset_of!(rlVertexBuffer, vaoId) - 48usize];
    ["Offset of field: rlVertexBuffer::vboId"]
        [::std::mem::offset_of!(rlVertexBuffer, vboId) - 52usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rlDrawCall {
    pub mode: ::std::os::raw::c_int,
    pub vertexCount: ::std::os::raw::c_int,
    pub vertexAlignment: ::std::os::raw::c_int,
    pub textureId: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rlDrawCall"][::std::mem::size_of::<rlDrawCall>() - 16usize];
    ["Alignment of rlDrawCall"][::std::mem::align_of::<rlDrawCall>() - 4usize];
    ["Offset of field: rlDrawCall::mode"][::std::mem::offset_of!(rlDrawCall, mode) - 0usize];
    ["Offset of field: rlDrawCall::vertexCount"]
        [::std::mem::offset_of!(rlDrawCall, vertexCount) - 4usize];
    ["Offset of field: rlDrawCall::vertexAlignment"]
        [::std::mem::offset_of!(rlDrawCall, vertexAlignment) - 8usize];
    ["Offset of field: rlDrawCall::textureId"]
        [::std::mem::offset_of!(rlDrawCall, textureId) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rlRenderBatch {
    pub bufferCount: ::std::os::raw::c_int,
    pub currentBuffer: ::std::os::raw::c_int,
    pub vertexBuffer: *mut rlVertexBuffer,
    pub draws: *mut rlDrawCall,
    pub drawCounter: ::std::os::raw::c_int,
    pub currentDepth: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rlRenderBatch"][::std::mem::size_of::<rlRenderBatch>() - 32usize];
    ["Alignment of rlRenderBatch"][::std::mem::align_of::<rlRenderBatch>() - 8usize];
    ["Offset of field: rlRenderBatch::bufferCount"]
        [::std::mem::offset_of!(rlRenderBatch, bufferCount) - 0usize];
    ["Offset of field: rlRenderBatch::currentBuffer"]
        [::std::mem::offset_of!(rlRenderBatch, currentBuffer) - 4usize];
    ["Offset of field: rlRenderBatch::vertexBuffer"]
        [::std::mem::offset_of!(rlRenderBatch, vertexBuffer) - 8usize];
    ["Offset of field: rlRenderBatch::draws"]
        [::std::mem::offset_of!(rlRenderBatch, draws) - 16usize];
    ["Offset of field: rlRenderBatch::drawCounter"]
        [::std::mem::offset_of!(rlRenderBatch, drawCounter) - 24usize];
    ["Offset of field: rlRenderBatch::currentDepth"]
        [::std::mem::offset_of!(rlRenderBatch, currentDepth) - 28usize];
};
pub const rlGlVersion_RL_OPENGL_SOFTWARE: rlGlVersion = 0;
pub const rlGlVersion_RL_OPENGL_11: rlGlVersion = 1;
pub const rlGlVersion_RL_OPENGL_21: rlGlVersion = 2;
pub const rlGlVersion_RL_OPENGL_33: rlGlVersion = 3;
pub const rlGlVersion_RL_OPENGL_43: rlGlVersion = 4;
pub const rlGlVersion_RL_OPENGL_ES_20: rlGlVersion = 5;
pub const rlGlVersion_RL_OPENGL_ES_30: rlGlVersion = 6;
pub type rlGlVersion = ::std::os::raw::c_uint;
pub const rlTraceLogLevel_RL_LOG_ALL: rlTraceLogLevel = 0;
pub const rlTraceLogLevel_RL_LOG_TRACE: rlTraceLogLevel = 1;
pub const rlTraceLogLevel_RL_LOG_DEBUG: rlTraceLogLevel = 2;
pub const rlTraceLogLevel_RL_LOG_INFO: rlTraceLogLevel = 3;
pub const rlTraceLogLevel_RL_LOG_WARNING: rlTraceLogLevel = 4;
pub const rlTraceLogLevel_RL_LOG_ERROR: rlTraceLogLevel = 5;
pub const rlTraceLogLevel_RL_LOG_FATAL: rlTraceLogLevel = 6;
pub const rlTraceLogLevel_RL_LOG_NONE: rlTraceLogLevel = 7;
pub type rlTraceLogLevel = ::std::os::raw::c_uint;
pub const rlPixelFormat_RL_PIXELFORMAT_UNCOMPRESSED_GRAYSCALE: rlPixelFormat = 1;
pub const rlPixelFormat_RL_PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA: rlPixelFormat = 2;
pub const rlPixelFormat_RL_PIXELFORMAT_UNCOMPRESSED_R5G6B5: rlPixelFormat = 3;
pub const rlPixelFormat_RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8: rlPixelFormat = 4;
pub const rlPixelFormat_RL_PIXELFORMAT_UNCOMPRESSED_R5G5B5A1: rlPixelFormat = 5;
pub const rlPixelFormat_RL_PIXELFORMAT_UNCOMPRESSED_R4G4B4A4: rlPixelFormat = 6;
pub const rlPixelFormat_RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8A8: rlPixelFormat = 7;
pub const rlPixelFormat_RL_PIXELFORMAT_UNCOMPRESSED_R32: rlPixelFormat = 8;
pub const rlPixelFormat_RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32: rlPixelFormat = 9;
pub const rlPixelFormat_RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32A32: rlPixelFormat = 10;
pub const rlPixelFormat_RL_PIXELFORMAT_UNCOMPRESSED_R16: rlPixelFormat = 11;
pub const rlPixelFormat_RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16: rlPixelFormat = 12;
pub const rlPixelFormat_RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16A16: rlPixelFormat = 13;
pub const rlPixelFormat_RL_PIXELFORMAT_COMPRESSED_DXT1_RGB: rlPixelFormat = 14;
pub const rlPixelFormat_RL_PIXELFORMAT_COMPRESSED_DXT1_RGBA: rlPixelFormat = 15;
pub const rlPixelFormat_RL_PIXELFORMAT_COMPRESSED_DXT3_RGBA: rlPixelFormat = 16;
pub const rlPixelFormat_RL_PIXELFORMAT_COMPRESSED_DXT5_RGBA: rlPixelFormat = 17;
pub const rlPixelFormat_RL_PIXELFORMAT_COMPRESSED_ETC1_RGB: rlPixelFormat = 18;
pub const rlPixelFormat_RL_PIXELFORMAT_COMPRESSED_ETC2_RGB: rlPixelFormat = 19;
pub const rlPixelFormat_RL_PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA: rlPixelFormat = 20;
pub const rlPixelFormat_RL_PIXELFORMAT_COMPRESSED_PVRT_RGB: rlPixelFormat = 21;
pub const rlPixelFormat_RL_PIXELFORMAT_COMPRESSED_PVRT_RGBA: rlPixelFormat = 22;
pub const rlPixelFormat_RL_PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA: rlPixelFormat = 23;
pub const rlPixelFormat_RL_PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA: rlPixelFormat = 24;
pub type rlPixelFormat = ::std::os::raw::c_uint;
pub const rlTextureFilter_RL_TEXTURE_FILTER_POINT: rlTextureFilter = 0;
pub const rlTextureFilter_RL_TEXTURE_FILTER_BILINEAR: rlTextureFilter = 1;
pub const rlTextureFilter_RL_TEXTURE_FILTER_TRILINEAR: rlTextureFilter = 2;
pub const rlTextureFilter_RL_TEXTURE_FILTER_ANISOTROPIC_4X: rlTextureFilter = 3;
pub const rlTextureFilter_RL_TEXTURE_FILTER_ANISOTROPIC_8X: rlTextureFilter = 4;
pub const rlTextureFilter_RL_TEXTURE_FILTER_ANISOTROPIC_16X: rlTextureFilter = 5;
pub type rlTextureFilter = ::std::os::raw::c_uint;
pub const rlBlendMode_RL_BLEND_ALPHA: rlBlendMode = 0;
pub const rlBlendMode_RL_BLEND_ADDITIVE: rlBlendMode = 1;
pub const rlBlendMode_RL_BLEND_MULTIPLIED: rlBlendMode = 2;
pub const rlBlendMode_RL_BLEND_ADD_COLORS: rlBlendMode = 3;
pub const rlBlendMode_RL_BLEND_SUBTRACT_COLORS: rlBlendMode = 4;
pub const rlBlendMode_RL_BLEND_ALPHA_PREMULTIPLY: rlBlendMode = 5;
pub const rlBlendMode_RL_BLEND_CUSTOM: rlBlendMode = 6;
pub const rlBlendMode_RL_BLEND_CUSTOM_SEPARATE: rlBlendMode = 7;
pub type rlBlendMode = ::std::os::raw::c_uint;
pub const rlShaderLocationIndex_RL_SHADER_LOC_VERTEX_POSITION: rlShaderLocationIndex = 0;
pub const rlShaderLocationIndex_RL_SHADER_LOC_VERTEX_TEXCOORD01: rlShaderLocationIndex = 1;
pub const rlShaderLocationIndex_RL_SHADER_LOC_VERTEX_TEXCOORD02: rlShaderLocationIndex = 2;
pub const rlShaderLocationIndex_RL_SHADER_LOC_VERTEX_NORMAL: rlShaderLocationIndex = 3;
pub const rlShaderLocationIndex_RL_SHADER_LOC_VERTEX_TANGENT: rlShaderLocationIndex = 4;
pub const rlShaderLocationIndex_RL_SHADER_LOC_VERTEX_COLOR: rlShaderLocationIndex = 5;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MATRIX_MVP: rlShaderLocationIndex = 6;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MATRIX_VIEW: rlShaderLocationIndex = 7;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MATRIX_PROJECTION: rlShaderLocationIndex = 8;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MATRIX_MODEL: rlShaderLocationIndex = 9;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MATRIX_NORMAL: rlShaderLocationIndex = 10;
pub const rlShaderLocationIndex_RL_SHADER_LOC_VECTOR_VIEW: rlShaderLocationIndex = 11;
pub const rlShaderLocationIndex_RL_SHADER_LOC_COLOR_DIFFUSE: rlShaderLocationIndex = 12;
pub const rlShaderLocationIndex_RL_SHADER_LOC_COLOR_SPECULAR: rlShaderLocationIndex = 13;
pub const rlShaderLocationIndex_RL_SHADER_LOC_COLOR_AMBIENT: rlShaderLocationIndex = 14;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MAP_ALBEDO: rlShaderLocationIndex = 15;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MAP_METALNESS: rlShaderLocationIndex = 16;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MAP_NORMAL: rlShaderLocationIndex = 17;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MAP_ROUGHNESS: rlShaderLocationIndex = 18;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MAP_OCCLUSION: rlShaderLocationIndex = 19;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MAP_EMISSION: rlShaderLocationIndex = 20;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MAP_HEIGHT: rlShaderLocationIndex = 21;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MAP_CUBEMAP: rlShaderLocationIndex = 22;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MAP_IRRADIANCE: rlShaderLocationIndex = 23;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MAP_PREFILTER: rlShaderLocationIndex = 24;
pub const rlShaderLocationIndex_RL_SHADER_LOC_MAP_BRDF: rlShaderLocationIndex = 25;
pub type rlShaderLocationIndex = ::std::os::raw::c_uint;
pub const rlShaderUniformDataType_RL_SHADER_UNIFORM_FLOAT: rlShaderUniformDataType = 0;
pub const rlShaderUniformDataType_RL_SHADER_UNIFORM_VEC2: rlShaderUniformDataType = 1;
pub const rlShaderUniformDataType_RL_SHADER_UNIFORM_VEC3: rlShaderUniformDataType = 2;
pub const rlShaderUniformDataType_RL_SHADER_UNIFORM_VEC4: rlShaderUniformDataType = 3;
pub const rlShaderUniformDataType_RL_SHADER_UNIFORM_INT: rlShaderUniformDataType = 4;
pub const rlShaderUniformDataType_RL_SHADER_UNIFORM_IVEC2: rlShaderUniformDataType = 5;
pub const rlShaderUniformDataType_RL_SHADER_UNIFORM_IVEC3: rlShaderUniformDataType = 6;
pub const rlShaderUniformDataType_RL_SHADER_UNIFORM_IVEC4: rlShaderUniformDataType = 7;
pub const rlShaderUniformDataType_RL_SHADER_UNIFORM_UINT: rlShaderUniformDataType = 8;
pub const rlShaderUniformDataType_RL_SHADER_UNIFORM_UIVEC2: rlShaderUniformDataType = 9;
pub const rlShaderUniformDataType_RL_SHADER_UNIFORM_UIVEC3: rlShaderUniformDataType = 10;
pub const rlShaderUniformDataType_RL_SHADER_UNIFORM_UIVEC4: rlShaderUniformDataType = 11;
pub const rlShaderUniformDataType_RL_SHADER_UNIFORM_SAMPLER2D: rlShaderUniformDataType = 12;
pub type rlShaderUniformDataType = ::std::os::raw::c_uint;
pub const rlShaderAttributeDataType_RL_SHADER_ATTRIB_FLOAT: rlShaderAttributeDataType = 0;
pub const rlShaderAttributeDataType_RL_SHADER_ATTRIB_VEC2: rlShaderAttributeDataType = 1;
pub const rlShaderAttributeDataType_RL_SHADER_ATTRIB_VEC3: rlShaderAttributeDataType = 2;
pub const rlShaderAttributeDataType_RL_SHADER_ATTRIB_VEC4: rlShaderAttributeDataType = 3;
pub type rlShaderAttributeDataType = ::std::os::raw::c_uint;
pub const rlFramebufferAttachType_RL_ATTACHMENT_COLOR_CHANNEL0: rlFramebufferAttachType = 0;
pub const rlFramebufferAttachType_RL_ATTACHMENT_COLOR_CHANNEL1: rlFramebufferAttachType = 1;
pub const rlFramebufferAttachType_RL_ATTACHMENT_COLOR_CHANNEL2: rlFramebufferAttachType = 2;
pub const rlFramebufferAttachType_RL_ATTACHMENT_COLOR_CHANNEL3: rlFramebufferAttachType = 3;
pub const rlFramebufferAttachType_RL_ATTACHMENT_COLOR_CHANNEL4: rlFramebufferAttachType = 4;
pub const rlFramebufferAttachType_RL_ATTACHMENT_COLOR_CHANNEL5: rlFramebufferAttachType = 5;
pub const rlFramebufferAttachType_RL_ATTACHMENT_COLOR_CHANNEL6: rlFramebufferAttachType = 6;
pub const rlFramebufferAttachType_RL_ATTACHMENT_COLOR_CHANNEL7: rlFramebufferAttachType = 7;
pub const rlFramebufferAttachType_RL_ATTACHMENT_DEPTH: rlFramebufferAttachType = 100;
pub const rlFramebufferAttachType_RL_ATTACHMENT_STENCIL: rlFramebufferAttachType = 200;
pub type rlFramebufferAttachType = ::std::os::raw::c_uint;
pub const rlFramebufferAttachTextureType_RL_ATTACHMENT_CUBEMAP_POSITIVE_X:
    rlFramebufferAttachTextureType = 0;
pub const rlFramebufferAttachTextureType_RL_ATTACHMENT_CUBEMAP_NEGATIVE_X:
    rlFramebufferAttachTextureType = 1;
pub const rlFramebufferAttachTextureType_RL_ATTACHMENT_CUBEMAP_POSITIVE_Y:
    rlFramebufferAttachTextureType = 2;
pub const rlFramebufferAttachTextureType_RL_ATTACHMENT_CUBEMAP_NEGATIVE_Y:
    rlFramebufferAttachTextureType = 3;
pub const rlFramebufferAttachTextureType_RL_ATTACHMENT_CUBEMAP_POSITIVE_Z:
    rlFramebufferAttachTextureType = 4;
pub const rlFramebufferAttachTextureType_RL_ATTACHMENT_CUBEMAP_NEGATIVE_Z:
    rlFramebufferAttachTextureType = 5;
pub const rlFramebufferAttachTextureType_RL_ATTACHMENT_TEXTURE2D: rlFramebufferAttachTextureType =
    100;
pub const rlFramebufferAttachTextureType_RL_ATTACHMENT_RENDERBUFFER:
    rlFramebufferAttachTextureType = 200;
pub type rlFramebufferAttachTextureType = ::std::os::raw::c_uint;
pub const rlCullMode_RL_CULL_FACE_FRONT: rlCullMode = 0;
pub const rlCullMode_RL_CULL_FACE_BACK: rlCullMode = 1;
pub type rlCullMode = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn rlMatrixMode(mode: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlPushMatrix();
}
unsafe extern "C" {
    pub fn rlPopMatrix();
}
unsafe extern "C" {
    pub fn rlLoadIdentity();
}
unsafe extern "C" {
    pub fn rlTranslatef(x: f32, y: f32, z: f32);
}
unsafe extern "C" {
    pub fn rlRotatef(angle: f32, x: f32, y: f32, z: f32);
}
unsafe extern "C" {
    pub fn rlScalef(x: f32, y: f32, z: f32);
}
unsafe extern "C" {
    pub fn rlMultMatrixf(matf: *const f32);
}
unsafe extern "C" {
    pub fn rlFrustum(left: f64, right: f64, bottom: f64, top: f64, znear: f64, zfar: f64);
}
unsafe extern "C" {
    pub fn rlOrtho(left: f64, right: f64, bottom: f64, top: f64, znear: f64, zfar: f64);
}
unsafe extern "C" {
    pub fn rlViewport(
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlSetClipPlanes(nearPlane: f64, farPlane: f64);
}
unsafe extern "C" {
    pub fn rlGetCullDistanceNear() -> f64;
}
unsafe extern "C" {
    pub fn rlGetCullDistanceFar() -> f64;
}
unsafe extern "C" {
    pub fn rlBegin(mode: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlEnd();
}
unsafe extern "C" {
    pub fn rlVertex2i(x: ::std::os::raw::c_int, y: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlVertex2f(x: f32, y: f32);
}
unsafe extern "C" {
    pub fn rlVertex3f(x: f32, y: f32, z: f32);
}
unsafe extern "C" {
    pub fn rlTexCoord2f(x: f32, y: f32);
}
unsafe extern "C" {
    pub fn rlNormal3f(x: f32, y: f32, z: f32);
}
unsafe extern "C" {
    pub fn rlColor4ub(
        r: ::std::os::raw::c_uchar,
        g: ::std::os::raw::c_uchar,
        b: ::std::os::raw::c_uchar,
        a: ::std::os::raw::c_uchar,
    );
}
unsafe extern "C" {
    pub fn rlColor3f(x: f32, y: f32, z: f32);
}
unsafe extern "C" {
    pub fn rlColor4f(x: f32, y: f32, z: f32, w: f32);
}
unsafe extern "C" {
    pub fn rlEnableVertexArray(vaoId: ::std::os::raw::c_uint) -> bool;
}
unsafe extern "C" {
    pub fn rlDisableVertexArray();
}
unsafe extern "C" {
    pub fn rlEnableVertexBuffer(id: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlDisableVertexBuffer();
}
unsafe extern "C" {
    pub fn rlEnableVertexBufferElement(id: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlDisableVertexBufferElement();
}
unsafe extern "C" {
    pub fn rlEnableVertexAttribute(index: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlDisableVertexAttribute(index: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlEnableStatePointer(
        vertexAttribType: ::std::os::raw::c_int,
        buffer: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn rlDisableStatePointer(vertexAttribType: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlActiveTextureSlot(slot: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlEnableTexture(id: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlDisableTexture();
}
unsafe extern "C" {
    pub fn rlEnableTextureCubemap(id: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlDisableTextureCubemap();
}
unsafe extern "C" {
    pub fn rlTextureParameters(
        id: ::std::os::raw::c_uint,
        param: ::std::os::raw::c_int,
        value: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlCubemapParameters(
        id: ::std::os::raw::c_uint,
        param: ::std::os::raw::c_int,
        value: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlEnableShader(id: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlDisableShader();
}
unsafe extern "C" {
    pub fn rlEnableFramebuffer(id: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlDisableFramebuffer();
}
unsafe extern "C" {
    pub fn rlGetActiveFramebuffer() -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlActiveDrawBuffers(count: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlBlitFramebuffer(
        srcX: ::std::os::raw::c_int,
        srcY: ::std::os::raw::c_int,
        srcWidth: ::std::os::raw::c_int,
        srcHeight: ::std::os::raw::c_int,
        dstX: ::std::os::raw::c_int,
        dstY: ::std::os::raw::c_int,
        dstWidth: ::std::os::raw::c_int,
        dstHeight: ::std::os::raw::c_int,
        bufferMask: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlBindFramebuffer(target: ::std::os::raw::c_uint, framebuffer: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlEnableColorBlend();
}
unsafe extern "C" {
    pub fn rlDisableColorBlend();
}
unsafe extern "C" {
    pub fn rlEnableDepthTest();
}
unsafe extern "C" {
    pub fn rlDisableDepthTest();
}
unsafe extern "C" {
    pub fn rlEnableDepthMask();
}
unsafe extern "C" {
    pub fn rlDisableDepthMask();
}
unsafe extern "C" {
    pub fn rlEnableBackfaceCulling();
}
unsafe extern "C" {
    pub fn rlDisableBackfaceCulling();
}
unsafe extern "C" {
    pub fn rlColorMask(r: bool, g: bool, b: bool, a: bool);
}
unsafe extern "C" {
    pub fn rlSetCullFace(mode: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlEnableScissorTest();
}
unsafe extern "C" {
    pub fn rlDisableScissorTest();
}
unsafe extern "C" {
    pub fn rlScissor(
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlEnablePointMode();
}
unsafe extern "C" {
    pub fn rlDisablePointMode();
}
unsafe extern "C" {
    pub fn rlSetPointSize(size: f32);
}
unsafe extern "C" {
    pub fn rlGetPointSize() -> f32;
}
unsafe extern "C" {
    pub fn rlEnableWireMode();
}
unsafe extern "C" {
    pub fn rlDisableWireMode();
}
unsafe extern "C" {
    pub fn rlSetLineWidth(width: f32);
}
unsafe extern "C" {
    pub fn rlGetLineWidth() -> f32;
}
unsafe extern "C" {
    pub fn rlEnableSmoothLines();
}
unsafe extern "C" {
    pub fn rlDisableSmoothLines();
}
unsafe extern "C" {
    pub fn rlEnableStereoRender();
}
unsafe extern "C" {
    pub fn rlDisableStereoRender();
}
unsafe extern "C" {
    pub fn rlIsStereoRenderEnabled() -> bool;
}
unsafe extern "C" {
    pub fn rlClearColor(
        r: ::std::os::raw::c_uchar,
        g: ::std::os::raw::c_uchar,
        b: ::std::os::raw::c_uchar,
        a: ::std::os::raw::c_uchar,
    );
}
unsafe extern "C" {
    pub fn rlClearScreenBuffers();
}
unsafe extern "C" {
    pub fn rlCheckErrors();
}
unsafe extern "C" {
    pub fn rlSetBlendMode(mode: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlSetBlendFactors(
        glSrcFactor: ::std::os::raw::c_int,
        glDstFactor: ::std::os::raw::c_int,
        glEquation: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlSetBlendFactorsSeparate(
        glSrcRGB: ::std::os::raw::c_int,
        glDstRGB: ::std::os::raw::c_int,
        glSrcAlpha: ::std::os::raw::c_int,
        glDstAlpha: ::std::os::raw::c_int,
        glEqRGB: ::std::os::raw::c_int,
        glEqAlpha: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlglInit(width: ::std::os::raw::c_int, height: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlglClose();
}
unsafe extern "C" {
    pub fn rlLoadExtensions(loader: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn rlGetProcAddress(procName: *const ::std::os::raw::c_char)
    -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn rlGetVersion() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rlSetFramebufferWidth(width: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlGetFramebufferWidth() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rlSetFramebufferHeight(height: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlGetFramebufferHeight() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rlGetTextureIdDefault() -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlGetShaderIdDefault() -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlGetShaderLocsDefault() -> *mut ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rlLoadRenderBatch(
        numBuffers: ::std::os::raw::c_int,
        bufferElements: ::std::os::raw::c_int,
    ) -> rlRenderBatch;
}
unsafe extern "C" {
    pub fn rlUnloadRenderBatch(batch: rlRenderBatch);
}
unsafe extern "C" {
    pub fn rlDrawRenderBatch(batch: *mut rlRenderBatch);
}
unsafe extern "C" {
    pub fn rlSetRenderBatchActive(batch: *mut rlRenderBatch);
}
unsafe extern "C" {
    pub fn rlDrawRenderBatchActive();
}
unsafe extern "C" {
    pub fn rlCheckRenderBatchLimit(vCount: ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn rlSetTexture(id: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlLoadVertexArray() -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlLoadVertexBuffer(
        buffer: *const ::std::os::raw::c_void,
        size: ::std::os::raw::c_int,
        dynamic: bool,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlLoadVertexBufferElement(
        buffer: *const ::std::os::raw::c_void,
        size: ::std::os::raw::c_int,
        dynamic: bool,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlUpdateVertexBuffer(
        bufferId: ::std::os::raw::c_uint,
        data: *const ::std::os::raw::c_void,
        dataSize: ::std::os::raw::c_int,
        offset: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlUpdateVertexBufferElements(
        id: ::std::os::raw::c_uint,
        data: *const ::std::os::raw::c_void,
        dataSize: ::std::os::raw::c_int,
        offset: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlUnloadVertexArray(vaoId: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlUnloadVertexBuffer(vboId: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlSetVertexAttribute(
        index: ::std::os::raw::c_uint,
        compSize: ::std::os::raw::c_int,
        type_: ::std::os::raw::c_int,
        normalized: bool,
        stride: ::std::os::raw::c_int,
        offset: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlSetVertexAttributeDivisor(
        index: ::std::os::raw::c_uint,
        divisor: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlSetVertexAttributeDefault(
        locIndex: ::std::os::raw::c_int,
        value: *const ::std::os::raw::c_void,
        attribType: ::std::os::raw::c_int,
        count: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlDrawVertexArray(offset: ::std::os::raw::c_int, count: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlDrawVertexArrayElements(
        offset: ::std::os::raw::c_int,
        count: ::std::os::raw::c_int,
        buffer: *const ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn rlDrawVertexArrayInstanced(
        offset: ::std::os::raw::c_int,
        count: ::std::os::raw::c_int,
        instances: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlDrawVertexArrayElementsInstanced(
        offset: ::std::os::raw::c_int,
        count: ::std::os::raw::c_int,
        buffer: *const ::std::os::raw::c_void,
        instances: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlLoadTexture(
        data: *const ::std::os::raw::c_void,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        format: ::std::os::raw::c_int,
        mipmapCount: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlLoadTextureDepth(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        useRenderBuffer: bool,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlLoadTextureCubemap(
        data: *const ::std::os::raw::c_void,
        size: ::std::os::raw::c_int,
        format: ::std::os::raw::c_int,
        mipmapCount: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlUpdateTexture(
        id: ::std::os::raw::c_uint,
        offsetX: ::std::os::raw::c_int,
        offsetY: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        format: ::std::os::raw::c_int,
        data: *const ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn rlGetGlTextureFormats(
        format: ::std::os::raw::c_int,
        glInternalFormat: *mut ::std::os::raw::c_uint,
        glFormat: *mut ::std::os::raw::c_uint,
        glType: *mut ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn rlGetPixelFormatName(format: ::std::os::raw::c_uint) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn rlUnloadTexture(id: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlGenTextureMipmaps(
        id: ::std::os::raw::c_uint,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        format: ::std::os::raw::c_int,
        mipmaps: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlReadTexturePixels(
        id: ::std::os::raw::c_uint,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        format: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn rlReadScreenPixels(
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_uchar;
}
unsafe extern "C" {
    pub fn rlLoadFramebuffer() -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlFramebufferAttach(
        id: ::std::os::raw::c_uint,
        texId: ::std::os::raw::c_uint,
        attachType: ::std::os::raw::c_int,
        texType: ::std::os::raw::c_int,
        mipLevel: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlFramebufferComplete(id: ::std::os::raw::c_uint) -> bool;
}
unsafe extern "C" {
    pub fn rlUnloadFramebuffer(id: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlCopyFramebuffer(
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        format: ::std::os::raw::c_int,
        pixels: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn rlResizeFramebuffer(width: ::std::os::raw::c_int, height: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlLoadShader(
        code: *const ::std::os::raw::c_char,
        type_: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlLoadShaderProgram(
        vsCode: *const ::std::os::raw::c_char,
        fsCode: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlLoadShaderProgramEx(
        vsId: ::std::os::raw::c_uint,
        fsId: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlLoadShaderProgramCompute(csId: ::std::os::raw::c_uint) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlUnloadShader(id: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlUnloadShaderProgram(id: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlGetLocationUniform(
        id: ::std::os::raw::c_uint,
        uniformName: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rlGetLocationAttrib(
        id: ::std::os::raw::c_uint,
        attribName: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rlSetUniform(
        locIndex: ::std::os::raw::c_int,
        value: *const ::std::os::raw::c_void,
        uniformType: ::std::os::raw::c_int,
        count: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlSetUniformMatrix(locIndex: ::std::os::raw::c_int, mat: Matrix);
}
unsafe extern "C" {
    pub fn rlSetUniformMatrices(
        locIndex: ::std::os::raw::c_int,
        mat: *const Matrix,
        count: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rlSetUniformSampler(locIndex: ::std::os::raw::c_int, textureId: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlSetShader(id: ::std::os::raw::c_uint, locs: *mut ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rlComputeShaderDispatch(
        groupX: ::std::os::raw::c_uint,
        groupY: ::std::os::raw::c_uint,
        groupZ: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn rlLoadShaderBuffer(
        size: ::std::os::raw::c_uint,
        data: *const ::std::os::raw::c_void,
        usageHint: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlUnloadShaderBuffer(ssboId: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlUpdateShaderBuffer(
        id: ::std::os::raw::c_uint,
        data: *const ::std::os::raw::c_void,
        dataSize: ::std::os::raw::c_uint,
        offset: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn rlBindShaderBuffer(id: ::std::os::raw::c_uint, index: ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn rlReadShaderBuffer(
        id: ::std::os::raw::c_uint,
        dest: *mut ::std::os::raw::c_void,
        count: ::std::os::raw::c_uint,
        offset: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn rlCopyShaderBuffer(
        destId: ::std::os::raw::c_uint,
        srcId: ::std::os::raw::c_uint,
        destOffset: ::std::os::raw::c_uint,
        srcOffset: ::std::os::raw::c_uint,
        count: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn rlGetShaderBufferSize(id: ::std::os::raw::c_uint) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rlBindImageTexture(
        id: ::std::os::raw::c_uint,
        index: ::std::os::raw::c_uint,
        format: ::std::os::raw::c_int,
        readonly: bool,
    );
}
unsafe extern "C" {
    pub fn rlGetMatrixModelview() -> Matrix;
}
unsafe extern "C" {
    pub fn rlGetMatrixProjection() -> Matrix;
}
unsafe extern "C" {
    pub fn rlGetMatrixTransform() -> Matrix;
}
unsafe extern "C" {
    pub fn rlGetMatrixProjectionStereo(eye: ::std::os::raw::c_int) -> Matrix;
}
unsafe extern "C" {
    pub fn rlGetMatrixViewOffsetStereo(eye: ::std::os::raw::c_int) -> Matrix;
}
unsafe extern "C" {
    pub fn rlSetMatrixProjection(proj: Matrix);
}
unsafe extern "C" {
    pub fn rlSetMatrixModelview(view: Matrix);
}
unsafe extern "C" {
    pub fn rlSetMatrixProjectionStereo(right: Matrix, left: Matrix);
}
unsafe extern "C" {
    pub fn rlSetMatrixViewOffsetStereo(right: Matrix, left: Matrix);
}
unsafe extern "C" {
    pub fn rlLoadDrawCube();
}
unsafe extern "C" {
    pub fn rlLoadDrawQuad();
}
